import "./globals.css";

export const metadata = {
  title: "Cardápio",
  description: "Generated by create next app - Luiz Otávio",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        {children}
      </body>
    </html>
  );
}
